"""
app/db/mongodb_adapter.py

MongoDB adapter — uses Motor (async wrapper around PyMongo).

Install: pip install motor

--- How MongoDB querying works in this system ---

SQL adapters receive a plain SQL string from query_builder.py.
MongoDB cannot use SQL, so query_builder.py detects the MongoDB adapter
and returns a JSON string instead:

    {
        "collection": "orders",
        "pipeline": [
            { "$match": { "region": "North" } },
            { "$group": { "_id": "$city", "sales": { "$sum": "$sales" } } },
            { "$sort":  { "sales": -1 } },
            { "$limit": 10 }
        ]
    }

This adapter parses that JSON and runs it as an aggregation pipeline.
"""

import json
import logging
import motor.motor_asyncio

from app.db.base import BaseDBAdapter
from app.config import settings

logger = logging.getLogger(__name__)


class MongoDBAdapter(BaseDBAdapter):

    def __init__(self):
        self._client: motor.motor_asyncio.AsyncIOMotorClient | None = None
        self._db = None

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def connect(self) -> None:
        logger.info("MongoDB connecting to: %s (db=%s)", settings.mongo_uri, settings.db_name)
        self._client = motor.motor_asyncio.AsyncIOMotorClient(
            settings.mongo_uri,
            serverSelectionTimeoutMS=settings.db_query_timeout_seconds * 1000,
        )
        self._db = self._client[settings.db_name]
        # Trigger an actual connection attempt to catch bad URIs early
        await self._client.admin.command("ping")
        logger.info("MongoDB connected.")

    async def disconnect(self) -> None:
        if self._client:
            self._client.close()
            self._client = None
            self._db = None
            logger.info("MongoDB disconnected.")

    # ------------------------------------------------------------------
    # Schema
    # ------------------------------------------------------------------

    async def get_schema(self) -> dict:
        """
        MongoDB is schemaless, so we sample up to 100 documents per
        collection and infer field names + types from them.

        The returned structure matches the standard format:
            { "collection_name": { "columns": [{"name": ..., "type": ...}] } }
        """
        self._require_connection()

        schema: dict = {}
        collection_names = await self._db.list_collection_names()

        for coll_name in collection_names:
            collection = self._db[coll_name]
            sample_docs = await collection.find({}, {"_id": 0}).limit(100).to_list(100)

            # Aggregate all field names and their observed Python types
            field_types: dict[str, set] = {}
            for doc in sample_docs:
                for key, value in doc.items():
                    field_types.setdefault(key, set())
                    field_types[key].add(type(value).__name__)

            columns = [
                {
                    "name": field,
                    "type": " | ".join(sorted(types)),  # e.g. "float | int"
                }
                for field, types in field_types.items()
            ]

            schema[coll_name] = {"columns": columns}

        return schema

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    async def run_query(self, query: str) -> list[dict]:
        """
        `query` must be a JSON string with shape:
            {
                "collection": "<name>",
                "pipeline":   [<aggregation stages>]
            }

        Example generated by query_builder.py:
            {
                "collection": "orders",
                "pipeline": [
                    { "$group": { "_id": "$region", "sales": { "$sum": "$sales" } } },
                    { "$sort":  { "sales": -1 } }
                ]
            }
        """
        self._require_connection()

        try:
            payload = json.loads(query)
        except json.JSONDecodeError as e:
            raise RuntimeError(
                f"MongoDBAdapter.run_query expects a JSON string, got: {query[:200]!r}"
            ) from e

        collection_name = payload.get("collection")
        pipeline = payload.get("pipeline", [])

        if not collection_name:
            raise RuntimeError("MongoDB query JSON must include a 'collection' key.")

        logger.debug("MongoDB aggregate on '%s': %s", collection_name, pipeline)

        try:
            collection = self._db[collection_name]
            cursor = collection.aggregate(pipeline)
            docs = await cursor.to_list(length=None)
            # Remove internal _id field and rename MongoDB group key
            return [_clean_doc(doc) for doc in docs]
        except Exception as e:
            logger.error("MongoDB aggregation error: %s | Pipeline: %s", e, pipeline)
            raise RuntimeError(f"MongoDB aggregation failed: {e}") from e

    # ------------------------------------------------------------------
    # Health
    # ------------------------------------------------------------------

    async def health_check(self) -> bool:
        try:
            self._require_connection()
            await self._client.admin.command("ping")
            return True
        except Exception:
            return False

    def _health_query(self) -> str:
        # Not used — health_check is overridden
        return ""

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _require_connection(self):
        if self._client is None or self._db is None:
            raise RuntimeError("MongoDBAdapter: connect() has not been called.")


def _clean_doc(doc: dict) -> dict:
    """
    Post-process a MongoDB aggregation result document:
    - Remove _id if it's None or an internal artefact.
    - Rename '_id' group key to the actual group field name when possible.
    """
    cleaned = {}
    for k, v in doc.items():
        if k == "_id":
            if isinstance(v, dict):
                # $group with multiple fields: { "_id": {"city": "$city"} }
                cleaned.update(v)
            elif v is not None:
                # $group by single field: { "_id": "North" }
                cleaned["group"] = v
            # Skip _id: None (count-only queries)
        else:
            cleaned[k] = v
    return cleaned